//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_Update
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STATIONDBEntities : DbContext
    {
        public STATIONDBEntities()
            : base("name=STATIONDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<service_version> service_version { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<setting_config> setting_config { get; set; }
        public virtual DbSet<station_data> station_data { get; set; }
        public virtual DbSet<station_installer> station_installer { get; set; }
    }
}
