//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_Update
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_version
    {
        public int id_station { get; set; }
        public string dispenser { get; set; }
        public string tankgauge { get; set; }
        public string monitor { get; set; }
        public string gaia { get; set; }
        public string api { get; set; }
        public string web_config { get; set; }
        public string web_suppot { get; set; }
    }
}
