//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_Update
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_installer
    {
        public int station_id { get; set; }
        public string station_pbl { get; set; }
        public string station_bu { get; set; }
        public string station_name { get; set; }
        public string station_ip { get; set; }
        public Nullable<bool> result_transfer { get; set; }
        public Nullable<bool> result_update { get; set; }
    }
}
