// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebSupportTeam.Data;

#nullable disable

namespace WebSupportTeam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230807075317_createTable")]
    partial class createTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("support")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebSupportTeam.Models.file_paths", b =>
                {
                    b.Property<int>("file_path_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("file_path_id"));

                    b.Property<string>("file_name")
                        .HasColumnType("text");

                    b.Property<string>("path_file")
                        .HasColumnType("text");

                    b.HasKey("file_path_id");

                    b.ToTable("file_path", "support");
                });

            modelBuilder.Entity("WebSupportTeam.Models.images", b =>
                {
                    b.Property<int?>("file_path_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("file_path_id"));

                    b.Property<string>("file_name")
                        .HasColumnType("text");

                    b.Property<string>("path_file")
                        .HasColumnType("text");

                    b.HasKey("file_path_id");

                    b.ToTable("image", "support");
                });

            modelBuilder.Entity("WebSupportTeam.Models.station_masters", b =>
                {
                    b.Property<int>("id_station")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_station"));

                    b.Property<string>("atg_alarm")
                        .HasColumnType("text");

                    b.Property<string>("brand_station")
                        .HasColumnType("text");

                    b.Property<string>("bu_station")
                        .HasColumnType("text");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ip_bo")
                        .HasColumnType("text");

                    b.Property<string>("ip_sim")
                        .HasColumnType("text");

                    b.Property<string>("name_station")
                        .HasColumnType("text");

                    b.Property<string>("pbl_station")
                        .HasColumnType("text");

                    b.Property<string>("pump_master")
                        .HasColumnType("text");

                    b.Property<string>("service_version")
                        .HasColumnType("text");

                    b.HasKey("id_station");

                    b.ToTable("station_master", "support");
                });

            modelBuilder.Entity("WebSupportTeam.Models.user_managers", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<string>("department")
                        .HasColumnType("text");

                    b.Property<bool>("enable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("login_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.Property<string>("user_name")
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("user_manager", "support");
                });
#pragma warning restore 612, 618
        }
    }
}
