// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebSupportTeam.Data;

#nullable disable

namespace WebSupportTeam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("support")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebSupportTeam.Models.File_path", b =>
                {
                    b.Property<int>("file_path_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("file_path_id"));

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("path_file")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("file_path_id");

                    b.ToTable("file_paths", "support");
                });

            modelBuilder.Entity("WebSupportTeam.Models.Images", b =>
                {
                    b.Property<int?>("file_path_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("file_path_id"));

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("path_file")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("file_path_id");

                    b.ToTable("images", "support");
                });

            modelBuilder.Entity("WebSupportTeam.Models.Station_master", b =>
                {
                    b.Property<int>("id_station")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_station"));

                    b.Property<string>("atg_alarm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("brand_station")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bu_station")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ip_bo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ip_sim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name_station")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pbl_station")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pump_master")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("service_version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_station");

                    b.ToTable("Station_masters", "support");
                });

            modelBuilder.Entity("WebSupportTeam.Models.Users_manager", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("enable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("login_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("Users_managers", "support");
                });
#pragma warning restore 612, 618
        }
    }
}
